// Generated by gencpp from file rt2_assignment1/CommandResponse.msg
// DO NOT EDIT!


#ifndef RT2_ASSIGNMENT1_MESSAGE_COMMANDRESPONSE_H
#define RT2_ASSIGNMENT1_MESSAGE_COMMANDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rt2_assignment1
{
template <class ContainerAllocator>
struct CommandResponse_
{
  typedef CommandResponse_<ContainerAllocator> Type;

  CommandResponse_()
    : ok(false)  {
    }
  CommandResponse_(const ContainerAllocator& _alloc)
    : ok(false)  {
  (void)_alloc;
    }



   typedef uint8_t _ok_type;
  _ok_type ok;





  typedef boost::shared_ptr< ::rt2_assignment1::CommandResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rt2_assignment1::CommandResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CommandResponse_

typedef ::rt2_assignment1::CommandResponse_<std::allocator<void> > CommandResponse;

typedef boost::shared_ptr< ::rt2_assignment1::CommandResponse > CommandResponsePtr;
typedef boost::shared_ptr< ::rt2_assignment1::CommandResponse const> CommandResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rt2_assignment1::CommandResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rt2_assignment1::CommandResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rt2_assignment1::CommandResponse_<ContainerAllocator1> & lhs, const ::rt2_assignment1::CommandResponse_<ContainerAllocator2> & rhs)
{
  return lhs.ok == rhs.ok;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rt2_assignment1::CommandResponse_<ContainerAllocator1> & lhs, const ::rt2_assignment1::CommandResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rt2_assignment1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rt2_assignment1::CommandResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rt2_assignment1::CommandResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rt2_assignment1::CommandResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rt2_assignment1::CommandResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rt2_assignment1::CommandResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rt2_assignment1::CommandResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rt2_assignment1::CommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6f6da3883749771fac40d6deb24a8c02";
  }

  static const char* value(const ::rt2_assignment1::CommandResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6f6da3883749771fULL;
  static const uint64_t static_value2 = 0xac40d6deb24a8c02ULL;
};

template<class ContainerAllocator>
struct DataType< ::rt2_assignment1::CommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rt2_assignment1/CommandResponse";
  }

  static const char* value(const ::rt2_assignment1::CommandResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rt2_assignment1::CommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool ok\n"
"\n"
;
  }

  static const char* value(const ::rt2_assignment1::CommandResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rt2_assignment1::CommandResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ok);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CommandResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rt2_assignment1::CommandResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rt2_assignment1::CommandResponse_<ContainerAllocator>& v)
  {
    s << indent << "ok: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ok);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RT2_ASSIGNMENT1_MESSAGE_COMMANDRESPONSE_H
