// Generated by gencpp from file rt2_assignment1/Position.msg
// DO NOT EDIT!


#ifndef RT2_ASSIGNMENT1_MESSAGE_POSITION_H
#define RT2_ASSIGNMENT1_MESSAGE_POSITION_H

#include <ros/service_traits.h>


#include <rt2_assignment1/PositionRequest.h>
#include <rt2_assignment1/PositionResponse.h>


namespace rt2_assignment1
{

struct Position
{

typedef PositionRequest Request;
typedef PositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Position
} // namespace rt2_assignment1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rt2_assignment1::Position > {
  static const char* value()
  {
    return "2f1d14ba96d90c01d836ab12b368aeb3";
  }

  static const char* value(const ::rt2_assignment1::Position&) { return value(); }
};

template<>
struct DataType< ::rt2_assignment1::Position > {
  static const char* value()
  {
    return "rt2_assignment1/Position";
  }

  static const char* value(const ::rt2_assignment1::Position&) { return value(); }
};


// service_traits::MD5Sum< ::rt2_assignment1::PositionRequest> should match
// service_traits::MD5Sum< ::rt2_assignment1::Position >
template<>
struct MD5Sum< ::rt2_assignment1::PositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rt2_assignment1::Position >::value();
  }
  static const char* value(const ::rt2_assignment1::PositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rt2_assignment1::PositionRequest> should match
// service_traits::DataType< ::rt2_assignment1::Position >
template<>
struct DataType< ::rt2_assignment1::PositionRequest>
{
  static const char* value()
  {
    return DataType< ::rt2_assignment1::Position >::value();
  }
  static const char* value(const ::rt2_assignment1::PositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rt2_assignment1::PositionResponse> should match
// service_traits::MD5Sum< ::rt2_assignment1::Position >
template<>
struct MD5Sum< ::rt2_assignment1::PositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rt2_assignment1::Position >::value();
  }
  static const char* value(const ::rt2_assignment1::PositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rt2_assignment1::PositionResponse> should match
// service_traits::DataType< ::rt2_assignment1::Position >
template<>
struct DataType< ::rt2_assignment1::PositionResponse>
{
  static const char* value()
  {
    return DataType< ::rt2_assignment1::Position >::value();
  }
  static const char* value(const ::rt2_assignment1::PositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RT2_ASSIGNMENT1_MESSAGE_POSITION_H
