// Generated by gencpp from file rt2_assignment1/RandomPositionRequest.msg
// DO NOT EDIT!


#ifndef RT2_ASSIGNMENT1_MESSAGE_RANDOMPOSITIONREQUEST_H
#define RT2_ASSIGNMENT1_MESSAGE_RANDOMPOSITIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rt2_assignment1
{
template <class ContainerAllocator>
struct RandomPositionRequest_
{
  typedef RandomPositionRequest_<ContainerAllocator> Type;

  RandomPositionRequest_()
    : x_max(0.0)
    , x_min(0.0)
    , y_max(0.0)
    , y_min(0.0)  {
    }
  RandomPositionRequest_(const ContainerAllocator& _alloc)
    : x_max(0.0)
    , x_min(0.0)
    , y_max(0.0)
    , y_min(0.0)  {
  (void)_alloc;
    }



   typedef float _x_max_type;
  _x_max_type x_max;

   typedef float _x_min_type;
  _x_min_type x_min;

   typedef float _y_max_type;
  _y_max_type y_max;

   typedef float _y_min_type;
  _y_min_type y_min;





  typedef boost::shared_ptr< ::rt2_assignment1::RandomPositionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rt2_assignment1::RandomPositionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RandomPositionRequest_

typedef ::rt2_assignment1::RandomPositionRequest_<std::allocator<void> > RandomPositionRequest;

typedef boost::shared_ptr< ::rt2_assignment1::RandomPositionRequest > RandomPositionRequestPtr;
typedef boost::shared_ptr< ::rt2_assignment1::RandomPositionRequest const> RandomPositionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rt2_assignment1::RandomPositionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rt2_assignment1::RandomPositionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rt2_assignment1::RandomPositionRequest_<ContainerAllocator1> & lhs, const ::rt2_assignment1::RandomPositionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.x_max == rhs.x_max &&
    lhs.x_min == rhs.x_min &&
    lhs.y_max == rhs.y_max &&
    lhs.y_min == rhs.y_min;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rt2_assignment1::RandomPositionRequest_<ContainerAllocator1> & lhs, const ::rt2_assignment1::RandomPositionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rt2_assignment1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rt2_assignment1::RandomPositionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rt2_assignment1::RandomPositionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rt2_assignment1::RandomPositionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rt2_assignment1::RandomPositionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rt2_assignment1::RandomPositionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rt2_assignment1::RandomPositionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rt2_assignment1::RandomPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "26f3066a0f42765f911db299f69f0138";
  }

  static const char* value(const ::rt2_assignment1::RandomPositionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x26f3066a0f42765fULL;
  static const uint64_t static_value2 = 0x911db299f69f0138ULL;
};

template<class ContainerAllocator>
struct DataType< ::rt2_assignment1::RandomPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rt2_assignment1/RandomPositionRequest";
  }

  static const char* value(const ::rt2_assignment1::RandomPositionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rt2_assignment1::RandomPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x_max\n"
"float32 x_min\n"
"float32 y_max\n"
"float32 y_min\n"
;
  }

  static const char* value(const ::rt2_assignment1::RandomPositionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rt2_assignment1::RandomPositionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x_max);
      stream.next(m.x_min);
      stream.next(m.y_max);
      stream.next(m.y_min);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RandomPositionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rt2_assignment1::RandomPositionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rt2_assignment1::RandomPositionRequest_<ContainerAllocator>& v)
  {
    s << indent << "x_max: ";
    Printer<float>::stream(s, indent + "  ", v.x_max);
    s << indent << "x_min: ";
    Printer<float>::stream(s, indent + "  ", v.x_min);
    s << indent << "y_max: ";
    Printer<float>::stream(s, indent + "  ", v.y_max);
    s << indent << "y_min: ";
    Printer<float>::stream(s, indent + "  ", v.y_min);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RT2_ASSIGNMENT1_MESSAGE_RANDOMPOSITIONREQUEST_H
